const products = window.PANACEA_PRODUCTS;
const money = value => new Intl.NumberFormat('uk-UA').format(value)+' ₴';
const quantities = Object.fromEntries(products.map(p=>[p.id,1]));
let cart={};
try {const saved=JSON.parse(localStorage.getItem('panacea-cart')||'{}'); for(const p of products) if(Number.isSafeInteger(saved[p.id])&&saved[p.id]>0)cart[p.id]=saved[p.id];}catch{}
const quantityHTML=(id,value,context)=>`<div class="quantity"><button data-step="-1" data-id="${id}" data-context="${context}" aria-label="Зменшити кількість">−</button><input aria-label="Кількість ${products.find(p=>p.id===id).brand}, ${products.find(p=>p.id===id).gas.toLowerCase()}, ${products.find(p=>p.id===id).material.toLowerCase()}" inputmode="numeric" type="number" min="1" step="1" value="${value}" data-id="${id}" data-context="${context}"><button data-step="1" data-id="${id}" data-context="${context}" aria-label="Збільшити кількість">+</button></div>`;
let activeBrand='all';
function renderProducts(){
 const query=document.querySelector('#search').value.trim().toLocaleLowerCase('uk-UA');
 const gases=[...document.querySelectorAll('input[name="gas"]:checked')].map(x=>x.value);
 const materials=[...document.querySelectorAll('input[name="material"]:checked')].map(x=>x.value);
 const selected=products.filter(p=>(activeBrand==='all'||p.brand===activeBrand)&&(!gases.length||gases.includes(p.gas))&&(!materials.length||materials.includes(p.material))&&('panacea '+p.brand+' '+p.category+' '+p.gas+' '+p.material+' 0,5 л').toLocaleLowerCase('uk-UA').includes(query));
 const sort=document.querySelector('#sort').value;
 if(sort!=='default')selected.sort((a,b)=>sort==='asc'?a.price-b.price:b.price-a.price);
 document.querySelector('#results-count').textContent=selected.length+' '+(selected.length===1?'товар':selected.length>=2&&selected.length<=4?'товари':'товарів');
 document.querySelector('#no-results').hidden=selected.length>0;
 document.querySelector('#product-grid').innerHTML=selected.map(p=>`<article class="product-card"><div class="product-photo ${p.brand==='Arden'?'arden':''}"><span class="product-material">${p.material==='Скло'?'У склі':'У банці'}</span><img class="${p.material==='Банка'?'can':''}" src="assets/products/${p.image}" alt="PANACEA ${p.brand}, ${p.gas.toLowerCase()}, ${p.material.toLowerCase()}, 0,5 л"><span class="product-volume">0,5 л</span></div><div class="product-info"><p class="product-type">${p.brand==='Arden'?'Мінеральна лікувально-столова':'Артезіанська питна вода'}</p><h2><a href="/product?id=${p.id}">PANACEA <span>${p.brand}</span></a></h2><p class="product-desc">${p.gas} · ${p.material.toLowerCase()} · 0,5 л</p><div class="buy-row"><div class="price">${money(p.price)}<small>/ шт.</small></div>${quantityHTML(p.id,quantities[p.id],'product')}</div><button class="add" data-add="${p.id}">До кошика <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></svg></button></div></article>`).join('');
}
function resetFilters(){activeBrand='all';document.querySelector('#search').value='';document.querySelectorAll('.sidebar input').forEach(x=>x.checked=false);document.querySelector('#mobile-gas').value='all';document.querySelector('#mobile-material').value='all';syncBrands();renderProducts();}
function syncBrands(){document.querySelectorAll('[data-brand]').forEach(b=>{const active=b.dataset.brand===activeBrand;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
document.querySelector('.search').addEventListener('submit',e=>{e.preventDefault();renderProducts();document.querySelector('#products').scrollIntoView({behavior:'smooth'});});
document.querySelector('#search').addEventListener('input',renderProducts);
document.querySelector('#sort').addEventListener('change',renderProducts);
document.querySelectorAll('.sidebar input').forEach(x=>x.addEventListener('change',()=>{const checked=[...document.querySelectorAll('input[name="'+x.name+'"]:checked')];document.querySelector('#mobile-'+x.name).value=checked.length===1?checked[0].value:'all';renderProducts();}));
document.querySelectorAll('#mobile-filters select').forEach(x=>x.addEventListener('change',()=>{const name=x.id.replace('mobile-','');document.querySelectorAll('input[name="'+name+'"]').forEach(input=>input.checked=input.value===x.value);renderProducts();}));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.brand){activeBrand=b.dataset.brand;syncBrands();renderProducts();}if(b.hasAttribute('data-reset'))resetFilters();if(b.matches('.mobile-filter')){const panel=document.querySelector('#mobile-filters');panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',String(!panel.hidden));}});
renderProducts();
function renderCart(){const count=Object.values(cart).reduce((a,b)=>a+b,0);document.querySelector('#cart-count').textContent=count;try{localStorage.setItem('panacea-cart',JSON.stringify(cart));}catch{}}
let toastTimer;function addToCart(id,quantity){if(!products.some(p=>p.id===id)||!Number.isSafeInteger(quantity)||quantity<1||!Number.isSafeInteger((cart[id]||0)+quantity))throw new Error('Некоректний товар або кількість');cart[id]=(cart[id]||0)+quantity;renderCart();const toast=document.querySelector('#toast');toast.textContent=`Додано до кошика: ${quantity} шт.`;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2500);return {items:{...cart}};}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.add){const input=b.closest("article").querySelector(".quantity input");const entered=Number(input.value);if(Number.isSafeInteger(entered)&&entered>=1)quantities[b.dataset.add]=entered;input.value=quantities[b.dataset.add];addToCart(b.dataset.add,quantities[b.dataset.add]);}if(b.dataset.step){const next=quantities[b.dataset.id]+Number(b.dataset.step);if(Number.isSafeInteger(next)&&next>=1){quantities[b.dataset.id]=next;b.parentElement.querySelector('input').value=next;}}});
document.addEventListener('change',event=>{const input=event.target;if(!input.matches('.quantity input'))return;const value=Number(input.value);if(Number.isSafeInteger(value)&&value>=1)quantities[input.dataset.id]=value;input.value=quantities[input.dataset.id];});
renderCart();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_products_to_cart',description:'Додати вибраний товар PANACEA до кошика. Не оформлює замовлення.',inputSchema:{type:'object',properties:{productId:{type:'string',enum:products.map(p=>p.id)},quantity:{type:'integer',minimum:1}},required:['productId','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>addToCart(input.productId,input.quantity)})).catch(()=>{});}catch{}}

